/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *notebook1;
  GtkWidget *fixed4;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *user;
  GtkWidget *psw;
  GtkWidget *label28;
  GtkWidget *msg;
  GtkWidget *login;
  GtkWidget *signin;
  GtkWidget *label15;
  GtkWidget *fixed1;
  GtkWidget *label6;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *label11;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *Nom;
  GtkWidget *Prenom;
  GtkWidget *Numtelephone;
  GtkWidget *Adressemail;
  GtkWidget *Motdepasse;
  GtkWidget *Verificationmotdepasse;
  GtkObject *Jour_adj;
  GtkWidget *Jour;
  GtkObject *Mois_adj;
  GtkWidget *Mois;
  GtkObject *An_adj;
  GtkWidget *An;
  GtkWidget *label10;
  GtkWidget *label12;
  GtkWidget *label5;
  GtkWidget *Homme;
  GSList *Homme_group = NULL;
  GtkWidget *Femme;
  GtkWidget *Valider;
  GtkWidget *Modepaiement;
  GtkWidget *label1;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (window1), notebook1);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  label29 = gtk_label_new (_("Adresse mail"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed4), label29, 144, 256);
  gtk_widget_set_size_request (label29, 150, 25);

  label30 = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed4), label30, 144, 328);
  gtk_widget_set_size_request (label30, 150, 25);

  user = gtk_entry_new ();
  gtk_widget_show (user);
  gtk_fixed_put (GTK_FIXED (fixed4), user, 360, 256);
  gtk_widget_set_size_request (user, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (user), 8226);

  psw = gtk_entry_new ();
  gtk_widget_show (psw);
  gtk_fixed_put (GTK_FIXED (fixed4), psw, 360, 328);
  gtk_widget_set_size_request (psw, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (psw), 8226);

  label28 = gtk_label_new (_("LogIn"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed4), label28, 528, 56);
  gtk_widget_set_size_request (label28, 150, 50);

  msg = gtk_label_new ("");
  gtk_widget_show (msg);
  gtk_fixed_put (GTK_FIXED (fixed4), msg, 216, 520);
  gtk_widget_set_size_request (msg, 500, 250);

  login = gtk_button_new_with_mnemonic (_("login\n"));
  gtk_widget_show (login);
  gtk_fixed_put (GTK_FIXED (fixed4), login, 904, 408);
  gtk_widget_set_size_request (login, 90, 35);

  signin = gtk_button_new_with_mnemonic (_("signin"));
  gtk_widget_show (signin);
  gtk_fixed_put (GTK_FIXED (fixed4), signin, 904, 448);
  gtk_widget_set_size_request (signin, 90, 35);

  label15 = gtk_label_new (_("   LOGIN   "));
  gtk_widget_show (label15);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label15);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed1);

  label6 = gtk_label_new (_("Nom"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed1), label6, 240, 184);
  gtk_widget_set_size_request (label6, 150, 25);

  label7 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed1), label7, 240, 248);
  gtk_widget_set_size_request (label7, 150, 25);

  label8 = gtk_label_new (_("Date de naissance"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed1), label8, 240, 312);
  gtk_widget_set_size_request (label8, 150, 25);

  label9 = gtk_label_new (_("Num telephone"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed1), label9, 240, 376);
  gtk_widget_set_size_request (label9, 150, 25);

  label11 = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed1), label11, 240, 504);
  gtk_widget_set_size_request (label11, 150, 25);

  label13 = gtk_label_new (_("Sexe"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed1), label13, 240, 624);
  gtk_widget_set_size_request (label13, 150, 25);

  label14 = gtk_label_new (_("Mode de paiement"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed1), label14, 240, 688);
  gtk_widget_set_size_request (label14, 200, 25);

  Nom = gtk_entry_new ();
  gtk_widget_show (Nom);
  gtk_fixed_put (GTK_FIXED (fixed1), Nom, 528, 184);
  gtk_widget_set_size_request (Nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (Nom), 8226);

  Prenom = gtk_entry_new ();
  gtk_widget_show (Prenom);
  gtk_fixed_put (GTK_FIXED (fixed1), Prenom, 528, 240);
  gtk_widget_set_size_request (Prenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (Prenom), 8226);

  Numtelephone = gtk_entry_new ();
  gtk_widget_show (Numtelephone);
  gtk_fixed_put (GTK_FIXED (fixed1), Numtelephone, 528, 368);
  gtk_widget_set_size_request (Numtelephone, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (Numtelephone), 8226);

  Adressemail = gtk_entry_new ();
  gtk_widget_show (Adressemail);
  gtk_fixed_put (GTK_FIXED (fixed1), Adressemail, 528, 432);
  gtk_widget_set_size_request (Adressemail, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (Adressemail), 8226);

  Motdepasse = gtk_entry_new ();
  gtk_widget_show (Motdepasse);
  gtk_fixed_put (GTK_FIXED (fixed1), Motdepasse, 528, 496);
  gtk_widget_set_size_request (Motdepasse, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (Motdepasse), 8226);

  Verificationmotdepasse = gtk_entry_new ();
  gtk_widget_show (Verificationmotdepasse);
  gtk_fixed_put (GTK_FIXED (fixed1), Verificationmotdepasse, 528, 560);
  gtk_widget_set_size_request (Verificationmotdepasse, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (Verificationmotdepasse), 8226);

  Jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  Jour = gtk_spin_button_new (GTK_ADJUSTMENT (Jour_adj), 1, 0);
  gtk_widget_show (Jour);
  gtk_fixed_put (GTK_FIXED (fixed1), Jour, 520, 304);
  gtk_widget_set_size_request (Jour, 60, 27);

  Mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  Mois = gtk_spin_button_new (GTK_ADJUSTMENT (Mois_adj), 1, 0);
  gtk_widget_show (Mois);
  gtk_fixed_put (GTK_FIXED (fixed1), Mois, 592, 304);
  gtk_widget_set_size_request (Mois, 60, 27);

  An_adj = gtk_adjustment_new (1, 1950, 2005, 1, 10, 10);
  An = gtk_spin_button_new (GTK_ADJUSTMENT (An_adj), 1, 0);
  gtk_widget_show (An);
  gtk_fixed_put (GTK_FIXED (fixed1), An, 664, 304);
  gtk_widget_set_size_request (An, 60, 27);

  label10 = gtk_label_new (_("Adresse mail"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed1), label10, 240, 440);
  gtk_widget_set_size_request (label10, 150, 25);

  label12 = gtk_label_new (_("Verification mot de passe"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed1), label12, 240, 568);
  gtk_widget_set_size_request (label12, 200, 25);

  label5 = gtk_label_new (_("SignIN"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed1), label5, 568, 64);
  gtk_widget_set_size_request (label5, 80, 25);

  Homme = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (Homme);
  gtk_fixed_put (GTK_FIXED (fixed1), Homme, 520, 624);
  gtk_widget_set_size_request (Homme, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (Homme), Homme_group);
  Homme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (Homme));

  Femme = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (Femme);
  gtk_fixed_put (GTK_FIXED (fixed1), Femme, 656, 624);
  gtk_widget_set_size_request (Femme, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (Femme), Homme_group);
  Homme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (Femme));

  Valider = gtk_button_new_with_mnemonic (_("valider"));
  gtk_widget_show (Valider);
  gtk_fixed_put (GTK_FIXED (fixed1), Valider, 824, 728);
  gtk_widget_set_size_request (Valider, 90, 35);

  Modepaiement = gtk_combo_box_new_text ();
  gtk_widget_show (Modepaiement);
  gtk_fixed_put (GTK_FIXED (fixed1), Modepaiement, 520, 680);
  gtk_widget_set_size_request (Modepaiement, 160, 27);
  gtk_combo_box_append_text (GTK_COMBO_BOX (Modepaiement), _("Par_jour_5DT"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (Modepaiement), _("Par_mois_150DT"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (Modepaiement), _("Par_trimestre_300DT"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (Modepaiement), _("Par_an _1000DT"));

  label1 = gtk_label_new (_("    SIGNIN     "));
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label1);

  g_signal_connect ((gpointer) login, "clicked",
                    G_CALLBACK (on_login_clicked),
                    NULL);
  g_signal_connect ((gpointer) signin, "clicked",
                    G_CALLBACK (on_signin_clicked),
                    NULL);
  g_signal_connect ((gpointer) Homme, "toggled",
                    G_CALLBACK (on_Homme_toggled),
                    NULL);
  g_signal_connect ((gpointer) Femme, "toggled",
                    G_CALLBACK (on_Femme_toggled),
                    NULL);
  g_signal_connect ((gpointer) Valider, "clicked",
                    G_CALLBACK (on_Valider_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window1, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window1, label29, "label29");
  GLADE_HOOKUP_OBJECT (window1, label30, "label30");
  GLADE_HOOKUP_OBJECT (window1, user, "user");
  GLADE_HOOKUP_OBJECT (window1, psw, "psw");
  GLADE_HOOKUP_OBJECT (window1, label28, "label28");
  GLADE_HOOKUP_OBJECT (window1, msg, "msg");
  GLADE_HOOKUP_OBJECT (window1, login, "login");
  GLADE_HOOKUP_OBJECT (window1, signin, "signin");
  GLADE_HOOKUP_OBJECT (window1, label15, "label15");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, label6, "label6");
  GLADE_HOOKUP_OBJECT (window1, label7, "label7");
  GLADE_HOOKUP_OBJECT (window1, label8, "label8");
  GLADE_HOOKUP_OBJECT (window1, label9, "label9");
  GLADE_HOOKUP_OBJECT (window1, label11, "label11");
  GLADE_HOOKUP_OBJECT (window1, label13, "label13");
  GLADE_HOOKUP_OBJECT (window1, label14, "label14");
  GLADE_HOOKUP_OBJECT (window1, Nom, "Nom");
  GLADE_HOOKUP_OBJECT (window1, Prenom, "Prenom");
  GLADE_HOOKUP_OBJECT (window1, Numtelephone, "Numtelephone");
  GLADE_HOOKUP_OBJECT (window1, Adressemail, "Adressemail");
  GLADE_HOOKUP_OBJECT (window1, Motdepasse, "Motdepasse");
  GLADE_HOOKUP_OBJECT (window1, Verificationmotdepasse, "Verificationmotdepasse");
  GLADE_HOOKUP_OBJECT (window1, Jour, "Jour");
  GLADE_HOOKUP_OBJECT (window1, Mois, "Mois");
  GLADE_HOOKUP_OBJECT (window1, An, "An");
  GLADE_HOOKUP_OBJECT (window1, label10, "label10");
  GLADE_HOOKUP_OBJECT (window1, label12, "label12");
  GLADE_HOOKUP_OBJECT (window1, label5, "label5");
  GLADE_HOOKUP_OBJECT (window1, Homme, "Homme");
  GLADE_HOOKUP_OBJECT (window1, Femme, "Femme");
  GLADE_HOOKUP_OBJECT (window1, Valider, "Valider");
  GLADE_HOOKUP_OBJECT (window1, Modepaiement, "Modepaiement");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");

  return window1;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed5;
  GtkWidget *label31;
  GtkWidget *treeview;
  GtkWidget *ModifierCompte;
  GtkWidget *ReserverParking;
  GtkWidget *actualiser;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (window2), fixed5);

  label31 = gtk_label_new (_("lInformations personnelles"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed5), label31, 296, 56);
  gtk_widget_set_size_request (label31, 200, 35);

  treeview = gtk_tree_view_new ();
  gtk_widget_show (treeview);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview, 40, 128);
  gtk_widget_set_size_request (treeview, 872, 296);

  ModifierCompte = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (ModifierCompte);
  gtk_fixed_put (GTK_FIXED (fixed5), ModifierCompte, 664, 472);
  gtk_widget_set_size_request (ModifierCompte, 100, 35);

  ReserverParking = gtk_button_new_with_mnemonic (_("Reserver\n"));
  gtk_widget_show (ReserverParking);
  gtk_fixed_put (GTK_FIXED (fixed5), ReserverParking, 104, 472);
  gtk_widget_set_size_request (ReserverParking, 100, 35);

  actualiser = gtk_button_new_with_mnemonic (_("actualiser"));
  gtk_widget_show (actualiser);
  gtk_fixed_put (GTK_FIXED (fixed5), actualiser, 344, 472);
  gtk_widget_set_size_request (actualiser, 104, 32);

  g_signal_connect ((gpointer) treeview, "row_activated",
                    G_CALLBACK (on_treeview_row_activated),
                    NULL);
  g_signal_connect ((gpointer) ModifierCompte, "clicked",
                    G_CALLBACK (on_ModifierCompte_clicked),
                    NULL);
  g_signal_connect ((gpointer) ReserverParking, "clicked",
                    G_CALLBACK (on_ReserverParking_clicked),
                    NULL);
  g_signal_connect ((gpointer) actualiser, "clicked",
                    G_CALLBACK (on_actualiser_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window2, label31, "label31");
  GLADE_HOOKUP_OBJECT (window2, treeview, "treeview");
  GLADE_HOOKUP_OBJECT (window2, ModifierCompte, "ModifierCompte");
  GLADE_HOOKUP_OBJECT (window2, ReserverParking, "ReserverParking");
  GLADE_HOOKUP_OBJECT (window2, actualiser, "actualiser");

  return window2;
}

GtkWidget*
create_window3 (void)
{
  GtkWidget *window3;
  GtkWidget *fixed6;
  GtkWidget *lqbel32;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *label33;
  GtkWidget *label36;
  GtkWidget *label37;
  GtkWidget *label39;
  GtkWidget *label38;
  GtkWidget *ModifNom;
  GtkWidget *ModifPrenom;
  GtkWidget *ModifNum;
  GtkWidget *Modifpsw;
  GtkWidget *ModifVerif;
  GtkObject *ModifJour_adj;
  GtkWidget *ModifJour;
  GtkObject *ModifMois_adj;
  GtkWidget *ModifMois;
  GtkObject *ModifAn_adj;
  GtkWidget *ModifAn;
  GtkWidget *SupprimerCmpt;
  GtkWidget *Enregistrer;
  GtkWidget *chercher;
  GtkWidget *ModifModeP;

  window3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window3), _("window3"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (window3), fixed6);

  lqbel32 = gtk_label_new (_("Modifier Compte"));
  gtk_widget_show (lqbel32);
  gtk_fixed_put (GTK_FIXED (fixed6), lqbel32, 256, 40);
  gtk_widget_set_size_request (lqbel32, 150, 40);

  label34 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed6), label34, 56, 160);
  gtk_widget_set_size_request (label34, 100, 25);

  label35 = gtk_label_new (_("Date de naissance"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed6), label35, 64, 200);
  gtk_widget_set_size_request (label35, 150, 25);

  label33 = gtk_label_new (_("Nom"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed6), label33, 48, 112);
  gtk_widget_set_size_request (label33, 100, 25);

  label36 = gtk_label_new (_("Num telephone"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed6), label36, 56, 240);
  gtk_widget_set_size_request (label36, 150, 25);

  label37 = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed6), label37, 48, 280);
  gtk_widget_set_size_request (label37, 150, 25);

  label39 = gtk_label_new (_("Verification de mot de passe "));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed6), label39, 72, 320);
  gtk_widget_set_size_request (label39, 200, 25);

  label38 = gtk_label_new (_("Mode de paiement"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed6), label38, 64, 360);
  gtk_widget_set_size_request (label38, 150, 25);

  ModifNom = gtk_entry_new ();
  gtk_widget_show (ModifNom);
  gtk_fixed_put (GTK_FIXED (fixed6), ModifNom, 296, 112);
  gtk_widget_set_size_request (ModifNom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ModifNom), 8226);

  ModifPrenom = gtk_entry_new ();
  gtk_widget_show (ModifPrenom);
  gtk_fixed_put (GTK_FIXED (fixed6), ModifPrenom, 296, 152);
  gtk_widget_set_size_request (ModifPrenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ModifPrenom), 8226);

  ModifNum = gtk_entry_new ();
  gtk_widget_show (ModifNum);
  gtk_fixed_put (GTK_FIXED (fixed6), ModifNum, 296, 232);
  gtk_widget_set_size_request (ModifNum, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ModifNum), 8226);

  Modifpsw = gtk_entry_new ();
  gtk_widget_show (Modifpsw);
  gtk_fixed_put (GTK_FIXED (fixed6), Modifpsw, 296, 272);
  gtk_widget_set_size_request (Modifpsw, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (Modifpsw), 8226);

  ModifVerif = gtk_entry_new ();
  gtk_widget_show (ModifVerif);
  gtk_fixed_put (GTK_FIXED (fixed6), ModifVerif, 296, 312);
  gtk_widget_set_size_request (ModifVerif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ModifVerif), 8226);

  ModifJour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  ModifJour = gtk_spin_button_new (GTK_ADJUSTMENT (ModifJour_adj), 1, 0);
  gtk_widget_show (ModifJour);
  gtk_fixed_put (GTK_FIXED (fixed6), ModifJour, 296, 192);
  gtk_widget_set_size_request (ModifJour, 60, 27);

  ModifMois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  ModifMois = gtk_spin_button_new (GTK_ADJUSTMENT (ModifMois_adj), 1, 0);
  gtk_widget_show (ModifMois);
  gtk_fixed_put (GTK_FIXED (fixed6), ModifMois, 368, 192);
  gtk_widget_set_size_request (ModifMois, 60, 27);

  ModifAn_adj = gtk_adjustment_new (1, 1950, 2005, 1, 10, 10);
  ModifAn = gtk_spin_button_new (GTK_ADJUSTMENT (ModifAn_adj), 1, 0);
  gtk_widget_show (ModifAn);
  gtk_fixed_put (GTK_FIXED (fixed6), ModifAn, 440, 192);
  gtk_widget_set_size_request (ModifAn, 60, 27);

  SupprimerCmpt = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (SupprimerCmpt);
  gtk_fixed_put (GTK_FIXED (fixed6), SupprimerCmpt, 456, 408);
  gtk_widget_set_size_request (SupprimerCmpt, 100, 30);

  Enregistrer = gtk_button_new_with_mnemonic (_("Enregistrer"));
  gtk_widget_show (Enregistrer);
  gtk_fixed_put (GTK_FIXED (fixed6), Enregistrer, 552, 408);
  gtk_widget_set_size_request (Enregistrer, 100, 30);

  chercher = gtk_button_new_with_mnemonic (_("chercher"));
  gtk_widget_show (chercher);
  gtk_fixed_put (GTK_FIXED (fixed6), chercher, 528, 120);
  gtk_widget_set_size_request (chercher, 66, 29);

  ModifModeP = gtk_combo_box_new_text ();
  gtk_widget_show (ModifModeP);
  gtk_fixed_put (GTK_FIXED (fixed6), ModifModeP, 296, 352);
  gtk_widget_set_size_request (ModifModeP, 150, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (ModifModeP), _("Par_jour_5DT"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ModifModeP), _("Par_mois_150DT"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ModifModeP), _("Par_trimestre_300DT"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ModifModeP), _("Par_an _1000DT"));

  g_signal_connect ((gpointer) SupprimerCmpt, "clicked",
                    G_CALLBACK (on_SupprimerCmpt_clicked),
                    NULL);
  g_signal_connect ((gpointer) Enregistrer, "clicked",
                    G_CALLBACK (on_Enregistrer_clicked),
                    NULL);
  g_signal_connect ((gpointer) chercher, "clicked",
                    G_CALLBACK (on_chercher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3, window3, "window3");
  GLADE_HOOKUP_OBJECT (window3, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window3, lqbel32, "lqbel32");
  GLADE_HOOKUP_OBJECT (window3, label34, "label34");
  GLADE_HOOKUP_OBJECT (window3, label35, "label35");
  GLADE_HOOKUP_OBJECT (window3, label33, "label33");
  GLADE_HOOKUP_OBJECT (window3, label36, "label36");
  GLADE_HOOKUP_OBJECT (window3, label37, "label37");
  GLADE_HOOKUP_OBJECT (window3, label39, "label39");
  GLADE_HOOKUP_OBJECT (window3, label38, "label38");
  GLADE_HOOKUP_OBJECT (window3, ModifNom, "ModifNom");
  GLADE_HOOKUP_OBJECT (window3, ModifPrenom, "ModifPrenom");
  GLADE_HOOKUP_OBJECT (window3, ModifNum, "ModifNum");
  GLADE_HOOKUP_OBJECT (window3, Modifpsw, "Modifpsw");
  GLADE_HOOKUP_OBJECT (window3, ModifVerif, "ModifVerif");
  GLADE_HOOKUP_OBJECT (window3, ModifJour, "ModifJour");
  GLADE_HOOKUP_OBJECT (window3, ModifMois, "ModifMois");
  GLADE_HOOKUP_OBJECT (window3, ModifAn, "ModifAn");
  GLADE_HOOKUP_OBJECT (window3, SupprimerCmpt, "SupprimerCmpt");
  GLADE_HOOKUP_OBJECT (window3, Enregistrer, "Enregistrer");
  GLADE_HOOKUP_OBJECT (window3, chercher, "chercher");
  GLADE_HOOKUP_OBJECT (window3, ModifModeP, "ModifModeP");

  return window3;
}

