/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *b_mainwindow;
  GtkWidget *b_ajoutaviswindow;
  GtkWidget *b_mesaviswindow;
  GtkWidget *b_modifaviswindow;
  GtkWidget *b_classementswindow;
  GtkWidget *b_avisdesutilisateurswindow;
  GtkWidget *gestion_reservation;
  GtkWidget *window1;
  GtkWidget *window2;
  GtkWidget *window3;
  GtkWidget *admincitoyen;
  GtkWidget *gerer;
  GtkWidget *gererparking;
  GtkWidget *ajoutdeparking;
  GtkWidget *supprimerparking;
  GtkWidget *modifierparking;
  GtkWidget *afficherparking;
  GtkWidget *gereraffectation_;
  GtkWidget *ajoutagent_;
  GtkWidget *affecteragent_;
  GtkWidget *afficheraffectation_;
  GtkWidget *espace_citoyen;
  GtkWidget *ajoutclient__;
  GtkWidget *suppressioncitoyen;
  GtkWidget *login;
  GtkWidget *afficher_citoyen;
  GtkWidget *calculer_facture;
  GtkWidget *modifiercitoyen;
  GtkWidget *logincitoyen;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  b_mainwindow = create_b_mainwindow ();
  gtk_widget_show (b_mainwindow);
  b_ajoutaviswindow = create_b_ajoutaviswindow ();
  gtk_widget_show (b_ajoutaviswindow);
  b_mesaviswindow = create_b_mesaviswindow ();
  gtk_widget_show (b_mesaviswindow);
  b_modifaviswindow = create_b_modifaviswindow ();
  gtk_widget_show (b_modifaviswindow);
  b_classementswindow = create_b_classementswindow ();
  gtk_widget_show (b_classementswindow);
  b_avisdesutilisateurswindow = create_b_avisdesutilisateurswindow ();
  gtk_widget_show (b_avisdesutilisateurswindow);
  gestion_reservation = create_gestion_reservation ();
  gtk_widget_show (gestion_reservation);
  window1 = create_window1 ();
  gtk_widget_show (window1);
  window2 = create_window2 ();
  gtk_widget_show (window2);
  window3 = create_window3 ();
  gtk_widget_show (window3);
  admincitoyen = create_admincitoyen ();
  gtk_widget_show (admincitoyen);
  gerer = create_gerer ();
  gtk_widget_show (gerer);
  gererparking = create_gererparking ();
  gtk_widget_show (gererparking);
  ajoutdeparking = create_ajoutdeparking ();
  gtk_widget_show (ajoutdeparking);
  supprimerparking = create_supprimerparking ();
  gtk_widget_show (supprimerparking);
  modifierparking = create_modifierparking ();
  gtk_widget_show (modifierparking);
  afficherparking = create_afficherparking ();
  gtk_widget_show (afficherparking);
  gereraffectation_ = create_gereraffectation_ ();
  gtk_widget_show (gereraffectation_);
  ajoutagent_ = create_ajoutagent_ ();
  gtk_widget_show (ajoutagent_);
  affecteragent_ = create_affecteragent_ ();
  gtk_widget_show (affecteragent_);
  afficheraffectation_ = create_afficheraffectation_ ();
  gtk_widget_show (afficheraffectation_);
  espace_citoyen = create_espace_citoyen ();
  gtk_widget_show (espace_citoyen);
  ajoutclient__ = create_ajoutclient__ ();
  gtk_widget_show (ajoutclient__);
  suppressioncitoyen = create_suppressioncitoyen ();
  gtk_widget_show (suppressioncitoyen);
  login = create_login ();
  gtk_widget_show (login);
  afficher_citoyen = create_afficher_citoyen ();
  gtk_widget_show (afficher_citoyen);
  calculer_facture = create_calculer_facture ();
  gtk_widget_show (calculer_facture);
  modifiercitoyen = create_modifiercitoyen ();
  gtk_widget_show (modifiercitoyen);
  logincitoyen = create_logincitoyen ();
  gtk_widget_show (logincitoyen);

  gtk_main ();
  return 0;
}

